name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main
      - "releases/*"

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-vcluster:
    name: Install vcluster CLI Test
    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest
        version:
          - v0.19.6
          - 0.20.0-beta.12
          - latest
          - ~
        kubectl-install:
          - true
          - false
        kubectl-version:
          - v1.28.2
          - 1.28.2
          - latest
          - ~
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Setup vCluster Action
        id: test-action
        uses: ./
        with:
          version: ${{ matrix.version }}
          kubectl-install: ${{ matrix.kubectl-install }}
          kubectl-version: ${{ matrix.kubectl-version }}

      - name: Print Version
        id: print-version
        run: vcluster version

      - name: Print Help
        id: print-help
        run: vcluster --help
